export default [
  {
    username: "Dimitri",
    catchPhrase: "Okidok",
    from: "Germany",
    age: 27,
  },
  {
    username: "Hugo",
    catchPhrase: "Fine by me",
    from: "UK",
    age: 30,
  },
  {
    username: "Alex",
    catchPhrase: "Smiles and more or less",
    from: "Spain",
    age: 31,
  },
  {
    username: "Soph",
    catchPhrase: "Theres so many moments that will forever be in our hearts",
    from: "Germany",
    age: 32,
  },
  {
    username: "Milena",
    catchPhrase: " I don't know how but it works",
    from: "Colombia",
    age: 17,
  },
  {
    username: "Marcel",
    catchPhrase: "It was only 9 euros",
    from: "Poland",
    age: 16,
  },
  { username: "Maxim", catchPhrase: "Yeaah dude", from: "Sweden", age: 22 },
  {
    username: "Marta",
    catchPhrase: "But look how prrrrretty it looks",
    from: "Spain",
    age: 78,
  },
  {
    username: "Gosia",
    catchPhrase: "Can I ask a question?",
    from: "Poland",
    age: 90,
  },
  {
    username: "Querien",
    catchPhrase: "Please don’t talk to me unless I’ve had coffee",
    from: "Netherlands",
    age: 32,
  },
  {
    username: "Monique",
    catchPhrase: "Yes, yes, yes",
    from: "Netherlands",
    age: 39,
  },
  {
    username: "Rosana",
    catchPhrase: "Can you push to github?",
    from: "Brazil",
    age: 22,
  },
  {
    username: "Filipe",
    catchPhrase: "Let's see...",
    from: "Portugal",
    age: 5,
  },
  {
    username: "Pauline",
    catchPhrase: "I love cheese",
    from: "France",
    age: 90,
  },
  {
    username: "Francisco",
    catchPhrase: "Say no to bootstrap",
    from: "Portugal",
    age: 16,
  },
  {
    username: "Franck",
    catchPhrase: "Let's rule this",
    from: "France",
    age: 7,
  },
  {
    username: "Jorge",
    catchPhrase: "Double thumbs up with lots of enthusiasm",
    from: "Venezuela",
    age: 64,
  },
  {
    username: "Vincenzo",
    catchPhrase: "Strongly worded email",
    from: "Italy",
    age: 2,
  },
  {
    username: "Marc",
    catchPhrase: "Sorry, I forgot to unmute myself",
    from: "Spain",
    age: 13,
  },
  {
    username: "Andre",
    catchPrase: "Can I get two thumbs up?",
    from: "Portugal",
    age: 87,
  },
];
